### ISSUE TITLE
Failed to reproduce results in the paper

### ISSUE THREAD

**Issue by mandal4** [FangShancheng/ABINet#16]
Thanks for release your source code.
Unfortunately, i got poor test result (about -4% from official results in the paper)

Is there any important training strategies to reproduce the results?
Or, is there anyone who meets same issue..?

**Comment by FangShancheng** [comment]
Thanks for reporting this issue, can you please provide your training environments and logs, and the accuracy on each dataset?
It is unlikely to have a big gap using this code and I'll try to find out the reason.

**Comment by FangShancheng** [comment]
@mandal4 Have you resolved this problem, or training details can be provided? 
Does the training images you use be cropped directly from original datasets, or after perspective transform?

**Comment by mandal4** [comment]
I found that my training environments are different with official setting

**Comment by FangShancheng** [comment]
Can you give the differences about the training environments that cause poor performance, which would be helpful.
