### ISSUE TITLE
使用其它数据集问题

### ISSUE THREAD

**Issue by swqsyy** [FangShancheng/ABINet#51]
想使用其他数据集，利用tools/create_lmdb_dataset.py将数据集转换成mdb格式后，不管是训练还是测试模型总是报错：
File "/home/yuy/workspace/ABINet-main/dataset.py", line 137, in __getitem__
    if not self.is_training: assert idx == idx_new, f'idx {idx} != idx_new {idx_new} during testing.'
AssertionError: idx 18 != idx_new 11558 during testing
想请问一下大概是什么原因呢？还是原始数据集需要做什么特殊处理吗？

**Comment by FangShancheng** [comment]
这个错应该是测试阶段发生的，测试阶段有测试数据被校验丢弃了

**Comment by swqsyy** [comment]
好的，非常感谢，已经解决问题了，就是这个原因

**Comment by lyc728** [comment]
> 试阶段有测试数据被校验丢弃了

请问你是怎么解决的呢？

**Comment by swqsyy** [comment]
> > 试阶段有测试数据被校验丢弃了
> 
> 请问你是怎么解决的呢？

修改校验部分和字符集，原有的校验部分会把字符集中没有的如符号之类的都删掉
