### ISSUE TITLE
   No module named 'fastai.callback.general_sched'

### ISSUE THREAD

**Issue by ncbwct** [FangShancheng/ABINet#7]
File "main.py", line 10, in <module>
    from fastai.callback.general_sched import GeneralScheduler, TrainingPhase
ModuleNotFoundError: No module named 'fastai.callback.general_sched'

**Comment by FangShancheng** [comment]
What is your fastai version, try to use our recommended version (requirement.txt) or directly use our Docker image.

**Comment by ncbwct** [comment]
thanks，It work for me

> pip install fastai==1.0.60   

>  pip install tensorboardX==0.8

**Comment by DemissieDaniel** [comment]
same problem,
 File "main.py", line 11, in <module>
    from fastai.callback.general_sched import GeneralScheduler, TrainingPhase
ModuleNotFoundError: No module named 'fastai.callback.general_sched'; 'fastai.callback' is not a package

**Comment by e41c9fp9duckcom** [comment]
from fastai.callbacks.general_sched import GeneralScheduler, TrainingPhase
ModuleNotFoundError: No module named 'fastai.callbacks'
