### ISSUE TITLE
 I set 100 epochs but training stops when I reach 10 epochs?

### ISSUE THREAD

**Issue by PhanTung-06** [FangShancheng/ABINet#79]
In configs file train_abinet.yaml, I set training epochs = 100 or 1000, but training stops when it reach 10 epochs?

**Comment by PhanTung-06** [comment]
![image](https://user-images.githubusercontent.com/62149695/188703293-74499d06-4681-4e28-8260-cb67e3183d58.png)

**Comment by PhanTung-06** [comment]
![image](https://user-images.githubusercontent.com/62149695/188703441-d30a40c1-9025-4a71-b857-4754d3ae2dd5.png)

**Comment by sneedgers** [comment]
Same issue here

**Comment by PhanTung-06** [comment]
> Same issue here

**Comment by anandpawara** [comment]
What was the solution? facing same issue

**Comment by PhanTung-06** [comment]
> What was the solution? facing same issue

I used python 3.7 and error. Upgrade to python 3.8 to work.

**Comment by nguyennampfiev** [comment]
I have same issue, @PhanTung-06 You can training over 10 epochs by just update python 3.8.

**Comment by anandpawara** [comment]
I guess it's nothing to do with python version, it didn't work for me as well
Try updating these values:
  scheduler: {
    periods: [6, 2],
    gamma: 0.1,
  }
Eg: suppose if you are training the model for 100 epochs, then update values in periods as [80,20] split which is 80+20 = 100,
this should work, which means 80 epochs for training and 20 epochs for evaluation, correct me if I am wrong
