### ISSUE TITLE
想问一下有没有中文模型相关的csv

### ISSUE THREAD

**Issue by 1193700079** [FangShancheng/ABINet#83]
问题一：
我通过自己生成的csv，训练出来，语言模型的loss为Nan
然后我看了一下wiktext-103的数据好像inp和gt的值都是一样的，不太能理解是什么意思

问题二：
如何自己更换相应的语言模型模块呢？用其他的bert的变体

**Comment by 1193700079** [comment]
ok  问题一 问题二 自己成功解决了 感谢ABINet的开源实现！

**Comment by lizhenye2017** [comment]
请问ABInet在中文数据集中的指标如何呢？请问用的是哪一个中文数据集呢？

**Comment by yisuanwang** [comment]
> ok 问题一 问题二 自己成功解决了 感谢ABINet的开源实现！

请问您用的是哪个中文数据集，请问对应的csv是什么样的呢，可以分享一下吗，感谢

**Comment by wu-yz** [comment]
> 问题一： 我通过自己生成的csv，训练出来，语言模型的loss为Nan 然后我看了一下wiktext-103的数据好像inp和gt的值都是一样的，不太能理解是什么意思
> 
> 问题二： 如何自己更换相应的语言模型模块呢？用其他的bert的变体

请问您咋解决的呀？

**Comment by wljoho** [comment]
> 请问ABInet在中文数据集中的指标如何呢？请问用的是哪一个中文数据集呢？

同问

**Comment by wljoho** [comment]
> ok 问题一 问题二 自己成功解决了 感谢ABINet的开源实现！

请问怎么解决的啊

**Comment by 1193700079** [comment]
> 请问ABInet在中文数据集中的指标如何呢？请问用的是哪一个中文数据集呢？

这个是自己的数据集 就是更改字符集相关的代码即可
