### ISSUE TITLE
模型在中文数据集上的效果讨论

### ISSUE THREAD

**Issue by xxAna** [FangShancheng/ABINet#9]
您好！非常感谢您们的工作和分享，请问如果想用这个模型在中文数据集上，会有哪些优劣吗？这里的语言模型要是换成中文的bert的话，效果影响大吗？您们是否有做过这方面的实验呢

**Comment by FangShancheng** [comment]
1. 中文数据集上目前只做了个小实验，（参见论文补充材料）

**Comment by FangShancheng** [comment]
> 您好！非常感谢您们的工作和分享，请问如果想用这个模型在中文数据集上，会有哪些优劣吗？这里的语言模型要是换成中文的bert的话，效果影响大吗？您们是否有做过这方面的实验呢

1. 中文数据集上目前只做了个小实验，（参见论文补充材料）
2. 不知道您说的中文BERT是啥意思，是完全按照BERT原文预训练的语言模型，还是按本文提出的语言模型在中文上预训练的？中文方面的实验，现在展开的不是很多，您有兴趣可以多尝试下。

**Comment by xxAna** [comment]
> 
> 
> > 您好！非常感谢您们的工作和分享，请问如果想用这个模型在中文数据集上，会有哪些优劣吗？这里的语言模型要是换成中文的bert的话，效果影响大吗？您们是否有做过这方面的实验呢
> 
>     1. 中文数据集上目前只做了个小实验，（参见论文补充材料）
> 
>     2. 不知道您说的中文BERT是啥意思，是完全按照BERT原文预训练的语言模型，还是按本文提出的语言模型在中文上预训练的？中文方面的实验，现在展开的不是很多，您有兴趣可以多尝试下。

好嘞，谢谢您的回复，我去看看。

**Comment by xxAna** [comment]
您好！我刚找了https://static.aminer.cn/storage/pdf/arxiv/21/2103/2103.06495.pdf这个版本的论文以及https://arxiv.org/pdf/2103.06495.pdf这个版本的，都没有找到您这里说的小实验呢，请问是还有别的正式版本吗？然后想请教下如果只是想初步看下在中文数据集上的效果，训练模型除了改字典还需要改哪些主要的地方呢？

**Comment by FangShancheng** [comment]
> 找了

您好，这里可以找到补充材料

**Comment by FangShancheng** [comment]
> 您好！我刚找了[https://static.aminer.cn/storage/pdf/arxiv/21/2103/2103.06495.pdf这个版本的论文以及https://arxiv.org/pdf/2103.06495.pdf这个版本的，都没有找到您这里说的小实验呢，请问是还有别的正式版本吗？然后想请教下如果只是想初步看下在中文数据集上的效果，训练模型除了改字典还需要改哪些主要的地方呢？](https://static.aminer.cn/storage/pdf/arxiv/21/2103/2103.06495.pdf%E8%BF%99%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84%E8%AE%BA%E6%96%87%E4%BB%A5%E5%8F%8Ahttps://arxiv.org/pdf/2103.06495.pdf%E8%BF%99%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84%EF%BC%8C%E9%83%BD%E6%B2%A1%E6%9C%89%E6%89%BE%E5%88%B0%E6%82%A8%E8%BF%99%E9%87%8C%E8%AF%B4%E7%9A%84%E5%B0%8F%E5%AE%9E%E9%AA%8C%E5%91%A2%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%98%AF%E8%BF%98%E6%9C%89%E5%88%AB%E7%9A%84%E6%AD%A3%E5%BC%8F%E7%89%88%E6%9C%AC%E5%90%97%EF%BC%9F%E7%84%B6%E5%90%8E%E6%83%B3%E8%AF%B7%E6%95%99%E4%B8%8B%E5%A6%82%E6%9E%9C%E5%8F%AA%E6%98%AF%E6%83%B3%E5%88%9D%E6%AD%A5%E7%9C%8B%E4%B8%8B%E5%9C%A8%E4%B8%AD%E6%96%87%E6%95%B0%E6%8D%AE%E9%9B%86%E4%B8%8A%E7%9A%84%E6%95%88%E6%9E%9C%EF%BC%8C%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E9%99%A4%E4%BA%86%E6%94%B9%E5%AD%97%E5%85%B8%E8%BF%98%E9%9C%80%E8%A6%81%E6%94%B9%E5%93%AA%E4%BA%9B%E4%B8%BB%E8%A6%81%E7%9A%84%E5%9C%B0%E6%96%B9%E5%91%A2%EF%BC%9F)

您好，这里可以找到补充材料https://openaccess.thecvf.com/content/CVPR2021/supplemental/Fang_Read_Like_Humans_CVPR_2021_supplemental.pdf
此外，主要是需要合成中文数据集。

**Comment by xxAna** [comment]
> 
> 
> > 您好！我刚找了[https://static.aminer.cn/storage/pdf/arxiv/21/2103/2103.06495.pdf这个版本的论文以及https://arxiv.org/pdf/2103.06495.pdf这个版本的，都没有找到您这里说的小实验呢，请问是还有别的正式版本吗？然后想请教下如果只是想初步看下在中文数据集上的效果，训练模型除了改字典还需要改哪些主要的地方呢？](https://static.aminer.cn/storage/pdf/arxiv/21/2103/2103.06495.pdf%E8%BF%99%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84%E8%AE%BA%E6%96%87%E4%BB%A5%E5%8F%8Ahttps://arxiv.org/pdf/2103.06495.pdf%E8%BF%99%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84%EF%BC%8C%E9%83%BD%E6%B2%A1%E6%9C%89%E6%89%BE%E5%88%B0%E6%82%A8%E8%BF%99%E9%87%8C%E8%AF%B4%E7%9A%84%E5%B0%8F%E5%AE%9E%E9%AA%8C%E5%91%A2%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%98%AF%E8%BF%98%E6%9C%89%E5%88%AB%E7%9A%84%E6%AD%A3%E5%BC%8F%E7%89%88%E6%9C%AC%E5%90%97%EF%BC%9F%E7%84%B6%E5%90%8E%E6%83%B3%E8%AF%B7%E6%95%99%E4%B8%8B%E5%A6%82%E6%9E%9C%E5%8F%AA%E6%98%AF%E6%83%B3%E5%88%9D%E6%AD%A5%E7%9C%8B%E4%B8%8B%E5%9C%A8%E4%B8%AD%E6%96%87%E6%95%B0%E6%8D%AE%E9%9B%86%E4%B8%8A%E7%9A%84%E6%95%88%E6%9E%9C%EF%BC%8C%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E9%99%A4%E4%BA%86%E6%94%B9%E5%AD%97%E5%85%B8%E8%BF%98%E9%9C%80%E8%A6%81%E6%94%B9%E5%93%AA%E4%BA%9B%E4%B8%BB%E8%A6%81%E7%9A%84%E5%9C%B0%E6%96%B9%E5%91%A2%EF%BC%9F)
> 
> 您好，这里可以找到补充材料https://openaccess.thecvf.com/content/CVPR2021/supplemental/Fang_Read_Like_Humans_CVPR_2021_supplemental.pdf
> 此外，主要是需要合成中文数据集。

好嘞，感谢您及时的回复！

**Comment by lyc728** [comment]
> 吗？您们是否有做过这方

这里想问下，为什么训练语言模型不直接加载bert的呢？他们也有直接训练的
